sonar.projectKey=Emaartapp-actions
sonar.organization=Momeek
sonar.projectName=Emaartapp-actions
sonar.host.url=https://sonarcloud.io

sonar.sources=client/src,nodeapi,javaapi/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/coverage/**,**/*.test.js

sonar.java.binaries=javaapi/target/classes

sonar.javascript.lcov.reportPaths=client/coverage/lcov.info
